config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"

  resources :books, only:[:new, :index, :show, :create, :destroy, :edit, :update]
  resources :users, only:[:show, :index, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body,  presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction,length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!, except: [:top,:about]
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id

        if @book.save
            flash[:notice] = "You have created book successfully.."
            redirect_to book_path(@book.id)
        else
            flash[:error] = @book.errors.full_messages
            redirect_to request.path
        end
    end

    def index
        @book = Book.all
        @user = current_user;
    end

    def show
        @book = Book.find(params[:id])
        @user = @book.user
    end

    def edit
        @book = Book.find(params[:id])
        unless current_user.id == @book.user_id
            redirect_to books_path
        end

    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice] = "You have updated book successfully."
            redirect_to book_path(@book.id)
        else
            flash[:book_edit_error] = @book.errors.full_messages
            render "edit"
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

    private

    def book_params
        params.require(:book).permit(:title, :body, :user_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      flash[:user_edit_error] = @user.errors.full_messages
      render "edit"
    end
  end

  def index
    @user = User.all;
  end


  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_index.html.erb
<h2 class="mt-2">New book</h2>

<%= form_with model: Book.new do |f| %>

  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title , class:"form-control" %>
  </div>

  <div class="form-group">
    <label for="book_body">Opnion</label>
    <%= f.text_field :body, class:"form-control" %>
  </div>

  <%= f.submit "Create Book"%>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if flash[:book_edit_error].present? %>
        <%= flash[:book_edit_error].length %>errors prohibited this obj from being saved:
        <ul>
          <% flash[:book_edit_error].each do |error| %>
          <li><%= error %></li>
      <% end %>
      </ul>
      <% end %>
      <%= form_with model: @book do |b| %>

      <div class="form-group">
        <label for="book_title">Title</label>
        <%= b.text_field :title ,class:"form-control"%>
      </div>

      <div class="form-group">
        <label for="book_body">Opnion</label>
        <%= b.text_field :body ,class:"form-control"%>
      </div>

      <div class="form-group">
        <%= b.submit "Update Book", class: "btn btn-success"%>
      </div>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
          <%= render "users/info", user: current_user %>
          <%= render "index" %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table">
            <thead>
              <tr>
                <th score="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Opinion</th>
              </tr>
            </thead>
            <tbody>
              <% @book.each do |data| %>
                <tr>
                  <% if data.user.profile_image.attached? %>
                    <td>
                      <%= link_to image_tag(data.user.profile_image, size: "100x100"), user_path(data.user_id) %>
                    </td>
                  <% else%>
                    <td>
                      <%= link_to image_tag("no_image", size: "150x150"),user_path(data.user_id) %>
                    </td>
                  <% end %>
                  <td><%= link_to data.title, book_path(data.id)%></td>
                  <td><%= data.body %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
          <%= render "users/info" ,user: @user %>
          <%= render "index" %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <% if @book.user.profile_image.attached? %>
                    <%= link_to image_tag(@book.user.profile_image, size: "100x100"), user_path(@book.user_id) %>
                  <% else%>
                    <%= link_to image_tag("no_image", size: "150x150"), user_path(@book.user_id) %>
                  <% end %>
                  <div>
                    <%= link_to @book.user.name, user_path(@book.user_id) %>
                  </div>
                </td>
                <td>
                  <%= link_to @book.title, book_path(@book.id)%>
                </td>
                <td>
                  <%= @book.body %>
                </td>
                <td>
                  <% if current_user.id == @book.user_id %>
                    <%= link_to "Edit", edit_book_path(@book.id) %>
                  <% end %>
                </td>
                <td>
                  <% if current_user.id == @book.user_id %>
                    <%= link_to "Destroy","/books/#{@book.id}",method: :delete, "data-confirm" => "本当に削除しますか？" %>
                  <% end %>
                </td>
              </tr>
          <table>
        </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Wellcome to
      <i class="fa-solid fa-book"></i>
      <b class="font-weight-bold">Bookers!</b>
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>
        wellcome to
        <i class="fa-solid fa-book"></i>
        <b class="font-weight-bold">Bookers!!</b>
      </h1>
      <p>
        In
        <i class="fa-solid fa-book"></i>
        Bookers,
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>

      <div class="btn-wappar col-10 mx-auto">
        <div class="row mb-3">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link href="https://use.fontawesome.com/releases/v6.2.0/css/all.css" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <%= link_to 'Bookers', root_path, class:"navbar-brand" %>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
            <i class="fa-solid fa-house"></i>
              Home
          <% end %>
          </li>
          <li class="nav-item">
            <%= link_to users_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-users"></i>
                Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to books_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-book-open"></i>
                Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path , method: :delete, class: "nav-link text-light" do %>
              <i class="fa-solid fa-right-from-bracket"></i>
                Log out
            <% end %>
          </li>
        <% else%>
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-house"></i>
                Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to about_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-link"></i>
                About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-user-plus"></i>
                Sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link text-light"  do %>
              <i class="fa-solid fa-right-to-bracket"></i>
              Log in
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
    <p class="notice"><%= notice %></p>
    <% if flash[:error].present? %>
      <%= flash[:error].length %>errors prohibited this obj from being saved:
    <ul>
      <% flash[:error].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>
    <%= yield %>
  </body>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <p class="mx-auto p-3">CopyRight Infratop.inc</p>
      </div>
    </div>
  </footer>
</html>

app/views/users/_info.html.erb
<h1>User info</h1>

<%if user.profile_image.attached? %>
  <%= image_tag user.profile_image, size: "150x150" %>
<% else %>
  <%= image_tag "no_image", size: "150x150" %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">name</th>
      <th scope="col"><%= user.name %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
  </tbody>
</table>
<%= link_to edit_user_path(user.id), class:"btn btn-outline-dark btn-block" do %>
  <i class="fa-solid fa-user-gear"></i>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <% if flash[:user_edit_error].present? %>
          <%= flash[:user_edit_error].length %>errors prohibited this obj from being saved:
          <ul>
            <% flash[:user_edit_error].each do |error| %>
            <li><%= error %></li>
            <% end %>
            </ul>
        <% end %>

      <%= form_with model: @user do |u| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= u.text_field :name, class:"form-control" %>
        </div>

        <div class="form-group">
          <label for="image">Image</label>
          <%= u.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
        </div>

        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= u.text_field :introduction,class:"form-control" %>
        </div>
        <%= u.submit "Update User",class: "btn btn-success"%>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
          <%= render "info", user: current_user %>
          <%= render "books/index" %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Users</h2>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">image</th>
                <th scope="col">name</th>
              </tr>
            </thead>
            <tbody>
              <% @user.each do |data| %>
                <tr>
                  <% if data.profile_image.attached? %>
                    <td><%= image_tag data.profile_image, size: "100x100" %></td>
                  <% else %>
                    <td><%= image_tag "no_image", size: "100x100" %></td>
                  <% end %>
                  <td><%= data.name %></td>
                  <td><%= link_to "Show", user_path(data.id) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
          <%= render "info" , user: @user%>
          <%= render "books/index" %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table">
            <thead>
              <tr>
                <th score="col"></th>
                <th scope="col">Title</th>
                <th scope="col">Opinion</th>
              </tr>
            </thead>
            <tbody>
              <% @user.books.each do |data| %>
                <tr>
                 <%if data.user.profile_image.attached? %>
                    <td>
                      <%= link_to image_tag(data.user.profile_image, size: "100x100"),user_path(data.id) %>
                    </td>
                <% else %>
                    <td>
                      <%= link_to image_tag("no_image", size: "100x100"),user_path(data.id) %>
                    </td>
                <% end %>
                  <td><%= link_to data.title, book_path(data.id)%></td>
                  <td><%= data.body %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    </div>
</div>